name: doctor_appointments
description: A Doctor Appointment Booking App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5 # For state management and routing
  shared_preferences: ^2.2.0 # For local storage
  http: ^1.1.0 # For API calls
  intl: ^0.19.0 # For date/time formatting
  flutter_svg: ^2.0.7 # For SVG images
  cached_network_image: ^3.2.3 # For image caching
  google_maps_flutter: ^2.3.0 # For maps
  table_calendar: ^3.0.9 # For calendar view  # flutter_local_notifications: ^15.1.0 # For local notifications - temporarily disabled
  sqflite: ^2.3.0 # For local database
  # timezone: ^0.9.2 # For timezone support in notifications - temporarily disabled

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
